version: '3.4'

services:
  ofo:
    image: datenlotse/ofo
    hostname: ofo
    ports:
      - 3000:3000
    environment: 
      WAIT_HOSTS: postgres:5432

  postgres:
    image: postgres
    hostname: postgres
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
    ports:
      - 5432