version: '3.4'

services:
  ofo:
    image: root
    depends_on: 
      - postgres
    ports:
      - 3000:3000
    environment: 
      WAIT_HOSTS: postgres:5432

  postgres:
    image: postgres
    environment:
      POSTGRES_USER: ofo
      POSTGRES_PASSWORD: postgres
    expose: 
      - 5432