# Use the latest 2.1 version of CircleCI pipeline process engine. See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1
# Use a package of configuration called an orb.
orbs:
  node: circleci/node@1.1.6
jobs:
  build-and-upload:
    executor:
      name: 'node/default'
    steps:
      - checkout
      - run: git submodule sync
      - run: git submodule update --init --recursive
      - create_concatenated_package_lock:
          filename: combined-package-lock.txt
      - restore_cache:
          keys:
            - v3-deps-{{ checksum "package-lock.json" }}-{{ checksum "combined-package-lock.txt" }}
            - v3-deps
      - node/with-cache:
          steps:
            - run:
                  name: Install dependencies
                  command: |
                    cd frontend
                    npm i
                    cd ../backend
                    npm i
            - run:
                name: Build frontend
                command: |
                  cd frontend
                  npm run build:prod
            - run:
                name: Move frontend to backend
                command: |
                  cd frontend
                  ls ../backend/src
                  cp ./dist/ofo-app/* ./backend/src/client/
            - run:
                name: Build backend
                command: |
                  cd backend
                  npm run build
            - store_artifacts:
                path: /backend/dist
            - run:
                name: Upload to releases
                command: |
                  ghr -t ${GITHUB_TOKEN} -u ${CIRCLE_PROJECT_USERNAME} -r ${CIRCLE_PROJECT_REPONAME} -c ${CIRCLE_SHA1} -delete ${VERSION} ./artifacts/
workflows:
    build-and-upload:
      jobs:
        - build-and-upload
        
commands:
        create_concatenated_package_lock:
        description: "Concatenate all package-lock.json files recognized by lerna.js into single file. File is used as checksum source for part of caching key."
    parameters:
      filename:
        type: string
    steps:
      - run:
          name: Combine package-lock.json files to single file
          command: npx lerna list -p -a | awk -F packages '{printf "\"packages%s/package-lock.json\" ", $2}' | xargs cat > << parameters.filename >>
