# Use the latest 2.1 version of CircleCI pipeline process engine. See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1
# Use a package of configuration called an orb.
orbs:
  node: circleci/node@1.1.6
jobs:
  build-and-upload:
    executor:
      name: 'node/default'
    steps:
      - checkout
      - node/with-cache:
        steps:
          - run:
              name: Install dependencies
              command: |
                cd frontend
                npm i
                npm i -g @angular/cli
                cd ../backend
                npm i
                npm i -g  @nest/cli
          - run:
              name: Build frontend
              command: |
                cd frontend
                ng build --prod
          - run:
              name: Move frontend to backend
              command: |
                cd frontend
                cp ./dist/ofo-app/* ../backend/src/client/
          - run:
              name: Build backend
              command: |
                cd backend
                npm run build
          - store_artifacts:
              path: /backend/dist
          - run:
              name: Upload to releases
              command: |
              ghr -t ${GITHUB_TOKEN} -u ${CIRCLE_PROJECT_USERNAME} -r ${CIRCLE_PROJECT_REPONAME} -c ${CIRCLE_SHA1} -delete ${VERSION} ./artifacts/

