# Use the latest 2.1 version of CircleCI pipeline process engine. See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1
# Use a package of configuration called an orb.
orbs:
  github: haskell-works/github-release@1.0.0
jobs:
  build-and-upload:
    docker:
      - image: docker
    steps:
      # Setup environment
      - setup_remote_docker:
          docker_layer_caching: true
      - restore_cache:
          keys:
            - v1-{{ .Branch }}
      - run:
          name: Load Docker image layer cache
          command: |
            set +o pipefail
            docker load -i /caches/ofo.tar | true
      - run:
          name: Build application Docker image
          command: |
            docker build --cache-from=app -t ofo https://github.com/Datenlotse/OFO.git
      - run:
          name: Save Docker image layer cache
          command: |
            mkdir -p /caches
            docker save -o /caches/ofo.tar ofo
      - save_cache:
          key: v1-{{ .Branch }}-{{ epoch }}
          paths:
            - /caches/ofo.tar
      - deploy:
          name: Push application Docker image
          command: |
            if [ "${CIRCLE_BRANCH}" == "master" ]; then
              docker login --username=${DOCKER_USERNAME} --password=${DOCKER_PASSWORD}
              docker tag ofo "datenlotse/ofo:${CIRCLE_SHA1}"
              docker push "datenlotse/ofo:${CIRCLE_SHA1}"
            fi
workflows:
    build-and-upload:
      jobs:
        - build-and-upload
